CREATE TABLE meetings (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    created_by BIGINT NOT NULL,
    participants ARRAY DEFAULT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    due_at TIMESTAMP(0) NOT NULL,
    language VARCHAR(64) NOT NULL,
    active BOOL NOT NULL DEFAULT TRUE
)